plugins {
    id 'fabric-loom' version '1.9+'
    id 'maven-publish'
    id 'com.gradleup.shadow' version '8.3.0+'
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

repositories {
    mavenCentral()
    maven {
        name = 'GriefDefender'
        url = 'https://repo.glaremasters.me/repository/bloodshot'
    }
    maven {
        name = 'LuckPerms'
        url = 'https://oss.sonatype.org/content/repositories/snapshots'
    }
    maven {
        name = 'Translations API'
        url = 'https://maven.nucleoid.xyz'
    }
    maven {
        name = 'WorldEdit'
        url = 'https://maven.enginehub.org/repo/'
    }
    maven {
        name = "BlueMap"
        url = 'https://jitpack.io'
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings "net.fabricmc:yarn:${yarn_mappings}:v2"
    modImplementation "net.fabricmc:fabric-loader:${loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"

    implementation include("org.iq80.leveldb:leveldb:${leveldb_version}")
    implementation include("org.iq80.leveldb:leveldb-api:${leveldb_version}")

    compileOnly "com.griefdefender:api:${griefdefender_version}"
    include(modImplementation("me.lucko:fabric-permissions-api:0.2-SNAPSHOT"))
    compileOnly "net.luckperms:api:${luckperms_version}"
    modImplementation include("xyz.nucleoid:server-translations-api:${servertranslations_version}")
    modImplementation "com.sk89q.worldedit:worldedit-fabric-mc${worldedit_version}"
    compileOnly "com.github.BlueMap-Minecraft:BlueMapAPI:${bluemap_version}"

    implementation 'org.jdbi:jdbi3-core:3.45.1'
    shadow 'org.jdbi:jdbi3-core:3.45.1'

    implementation "org.jdbi:jdbi3-jackson2:3.45.1"
    shadow "org.jdbi:jdbi3-jackson2:3.45.1"

    implementation 'org.postgresql:postgresql:42.7.2'
    shadow 'org.postgresql:postgresql:42.7.2'

    implementation 'com.zaxxer:HikariCP:5.1.0'
    shadow 'com.zaxxer:HikariCP:5.1.0'
}

processResources {
    inputs.property "version", project.version

    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

remapJar {
    dependsOn(shadowJar)
    mustRunAfter(shadowJar)
    inputFile = file(shadowJar.archivePath)
}

shadowJar {
    configurations = [project.configurations.shadow]
    mergeServiceFiles()
    exclude("META-INF")
}

tasks.build {
    dependsOn tasks.shadowJar
}

jar {
    from("LICENSE") {
        rename { "${it}_${project.archivesBaseName}"}
    }
}
